package nigellus.bookstore.entity;

import java.util.HashSet;
import java.util.Set;

// Generated Nov 26, 2014 10:52:05 AM by Hibernate Tools 3.4.0.CR1

/**
 * Book generated by hbm2java
 */
public class Book implements java.io.Serializable {

	private Integer id;
	private Category category;
	private String title;
	private float unitPrice;
	private String description;
	private String authorList;
	private String imageUrl;
	private Set categories = new HashSet(0);

	public Set getCategories() {
		return categories;
	}

	public void setCategories(Set categories) {
		this.categories = categories;
	}

	public Book() {
	}

	public Book(Category category, String title, float unitPrice,
			String authorList, String imageUrl) {
		this.category = category;
		this.title = title;
		this.unitPrice = unitPrice;
		this.authorList = authorList;
		this.imageUrl = imageUrl;
	}

	public Book(Category category, String title, float unitPrice,
			String description, String authorList, String imageUrl) {
		this.category = category;
		this.title = title;
		this.unitPrice = unitPrice;
		this.description = description;
		this.authorList = authorList;
		this.imageUrl = imageUrl;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public float getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(float unitPrice) {
		this.unitPrice = unitPrice;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getAuthorList() {
		return this.authorList;
	}

	public void setAuthorList(String authorList) {
		this.authorList = authorList;
	}

	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

}
