package nigellus.bookstore.entity;
// default package
// Generated Nov 30, 2014 2:46:00 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private String username;
	private String password;
	private String fullname;
	private String address;
	private String email;
	private String phone;
	private Set orders = new HashSet(0);

	public Customer() {
	}

	public Customer(String username, String password, String fullname) {
		this.username = username;
		this.password = password;
		this.fullname = fullname;
	}

	public Customer(String username, String password, String fullname,
			String address, String email, String phone, Set orders) {
		this.username = username;
		this.password = password;
		this.fullname = fullname;
		this.address = address;
		this.email = email;
		this.phone = phone;
		this.orders = orders;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Set getOrders() {
		return this.orders;
	}

	public void setOrders(Set orders) {
		this.orders = orders;
	}

}
