package nigellus.bookstore.entity;

// default package
// Generated Nov 30, 2014 2:46:00 PM by Hibernate Tools 3.4.0.CR1

/**
 * Orderdetails generated by hbm2java
 */
public class OrderDetail implements java.io.Serializable {

	private Integer id;
	private Book book;
	private Order order;

	private int quantity;

	public OrderDetail() {
	}

	public OrderDetail(Book book, int quantity) {

		this.book = book;
		this.quantity = quantity;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	public Order getOrder() {
		return order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public Book getBook() {
		return book;
	}

	public void setBook(Book book) {
		this.book = book;
	}
}
