package nigellus.bookstore.entity;
// default package
// Generated Nov 30, 2014 2:46:00 PM by Hibernate Tools 3.4.0.CR1

/**
 * Orderdetails generated by hbm2java
 */
public class OrderDetail implements java.io.Serializable {

	private Integer id;
	private Order order;
	private int bookId;
	private int quantity;

	public OrderDetail() {
	}

	public OrderDetail(Order order, int bookId, int quantity) {
		this.order = order;
		this.bookId = bookId;
		this.quantity = quantity;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	public int getBookId() {
		return this.bookId;
	}

	public void setBookId(int bookId) {
		this.bookId = bookId;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

}
