package nigellus.bookstore.entity;
// default package
// Generated Nov 30, 2014 2:46:00 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Order generated by hbm2java
 */
public class Order implements java.io.Serializable {

	private Integer id;
	private Customer customer;
	private String orderDate;
	private float totalAmount;
	private Set orderdetails = new HashSet(0);

	public Set getOrderdetails() {
		return orderdetails;
	}

	public void setOrderdetails(Set orderdetails) {
		this.orderdetails = orderdetails;
	}

	public Order() {
	}

	public Order(Customer customer, String orderDate, float totalAmount) {
		this.customer = customer;
		this.orderDate = orderDate;
		this.totalAmount = totalAmount;
	}

	public Order(Customer customer, String orderDate, float totalAmount,
			Set orderdetailses) {
		this.customer = customer;
		this.orderDate = orderDate;
		this.totalAmount = totalAmount;
		this.orderdetails = orderdetailses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(String orderDate) {
		this.orderDate = orderDate;
	}

	public float getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(float totalAmount) {
		this.totalAmount = totalAmount;
	}

}
